name: CI - Code Format Check

on:
  push:
    branches:
      - main
      - develop
      - ci
  pull_request:
    branches:
      - main
      - develop
      - ci

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Verify no format changes
        run: dotnet format --verify-no-changes
