name: CI - Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Install Required Tools
        run: |
          dotnet new tool-manifest
          dotnet add StarWars.Tests/StarWars.Tests.csproj package Moq

      - name: Build
        run: |
          dotnet build StarWars.Lib/StarWars.Lib.csproj --configuration Release
          dotnet build StarWars.Tests/StarWars.Tests.csproj --configuration Release

      - name: Test
        run: dotnet test ./SpaceBattle.Lib.Test/ --collect:"XPlat Code Coverage" --settings ./coverlet.runsettings --results-directory ./coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: true
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '20 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
